### ISSUE TITLE
how to setup the server's folder?

### ISSUE THREAD

**Issue by winsonet** [rknell/alfred#124]
for example, I want to put a HTML into the HTTP server, the HTML file put in the below  folder

```
/assets/upload_files/index.html
/assets/upload_files/css/style.css
/assets/upload_files/js/jquery.js
/assets/upload_files/js/main.js
```
I use the below code for creating the HTTP server but not working

```
final app = Alfred();

app.get('/*', (req, res) => Directory('/assets/upload_files'));

await app.listen();
```

my question is what's file path should I put to `Directory` ? it seem the path in the app doc folder in runtime, right?

I can only load one HTML file like below

```
final html =
                await rootBundle.loadString('assets/upload_files/index.html');
           app.get(
              '/*',
              (req, res) {
                res.headers.contentType = ContentType.html;
                return html;
              },
            );
```

but how can I load a folder with multiple files like js, CSS and HTML ? I don't know how to refer and set the path.

Thanks!

**Comment by rknell** [comment]
Hey @winsonet , Sorry I just realised I hadn't gotten back to you.

The example code in the second block looks perfect except that you are using a leading slash - that will take you to the root of the file system.

What I often do because i get confused is to pull that directory object out into its own variable and then print the absolute path, so something like

```dart
var dir = Directory('/assets/upload_files');
print(dir.absolute);
```

Thats pseudo code, but yeah, then you can work out where the directory is pointing and it should solve it for you.

**Comment by winsonet** [comment]
Thanks for your reply, but I still don't know how to setup the folder :(

 after run below 
```
var dir = Directory('/assets/upload_files');
print('absolute folder: ${dir.absolute}');
```
just show the folder what I pass:

```
absolute folder: '/assets/upload_files'
```

**Comment by rknell** [comment]
Try removing that leading slash and run it again ie 'assets/uploadFiles'

**Comment by winsonet** [comment]
I tried, but just same 

```dart
  var dir = Directory('assets/upload_files');
    print("absolute path: ${dir.absolute}");
```

output

```
flutter: absolute path: Directory: '/assets/upload_files'
```

**Comment by rknell** [comment]
Ah. Sorry I'm not near a machine I can run the code on. At the end of the day it's just a dart directory object and it's not part of Alfred.

According to this:
https://api.dart.dev/stable/3.1.4/dart-io/Directory-class.html

Absolute returns a directory object, so maybe print out directory.absolute.path

Other things you can try is creating a directory with a weird name and searching your system for where it's found. I won't be back with a machine until Monday to give a fully tested example

**Comment by rknell** [comment]
Edit. Maybe also try printing out the directory Uri? Directory.uri

**Comment by winsonet** [comment]
Thanks, but I found that `Directory` only can get the app's application documents directory, just the build in folder in the app, so should be can't access from the `assets` folder, I think the only way that I need to copy all of the assets files into application documents directory and pass to `alfred`

by the way, the `dir.uri` also can show the current document directory 

```dart
    var dir = Directory('/assets/upload_files');
    print("absolute path url: ${dir.uri}");
```

output

```
flutter: absolute path url: file:///assets/upload_files/
``` 

anyway, thanks!

**Comment by rknell** [comment]
@winsonet 

I've had a chance to look into the directory stuff and can confirm that this is working on my mac.

```dart
import 'dart:io';

import 'package:alfred/alfred.dart';

void main() async {
  final app = Alfred();

  /// Note the wildcard (*) this is very important!!
  app.get('/public/*', (req, res) => Directory('test/files'));

  app.get(
      '/publicAbsolute/*', (req, res) => Directory('/Users/ryanknell/Desktop'));

  app.get('/publicRelative/*', (req, res) => Directory('../quokki'));

  await app.listen();
}
```

So in this case Alfred had no trouble serving files using an absolute string, a relative string, and a relative string in the parent directory.

My mac did throw up a permission error trying to get to my downloads directory, but other than that it all worked as expected. Are you using another OS? there could be some OS specific thing regarding permissions or file path formats (ie windows) and the slashes being the wrong way perhaps?

**Comment by winsonet** [comment]
got it, thank you so much!
